// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfzpNjaxxwl80ZRN6XcNntlNN4A_0of4',
    appId: '1:1011835018311:web:3c8d1ea755de643467a562',
    messagingSenderId: '1011835018311',
    projectId: 'bookshelf-ed5a3',
    authDomain: 'bookshelf-ed5a3.firebaseapp.com',
    storageBucket: 'bookshelf-ed5a3.appspot.com',
    measurementId: 'G-NBR8EEPZGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo_BvVAefPkqYWHQrgYn3KPqIbzXi3XHc',
    appId: '1:1011835018311:android:657d7124d0d3f2ec67a562',
    messagingSenderId: '1011835018311',
    projectId: 'bookshelf-ed5a3',
    storageBucket: 'bookshelf-ed5a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkeNNr7tBhhITJ9tkNXKjmcky533CEDk4',
    appId: '1:1011835018311:ios:5da24a16c36c25a967a562',
    messagingSenderId: '1011835018311',
    projectId: 'bookshelf-ed5a3',
    storageBucket: 'bookshelf-ed5a3.appspot.com',
    iosClientId: '1011835018311-sbqnrlg7hds5opb2fulnsoshsdk1167n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkeNNr7tBhhITJ9tkNXKjmcky533CEDk4',
    appId: '1:1011835018311:ios:5da24a16c36c25a967a562',
    messagingSenderId: '1011835018311',
    projectId: 'bookshelf-ed5a3',
    storageBucket: 'bookshelf-ed5a3.appspot.com',
    iosClientId: '1011835018311-sbqnrlg7hds5opb2fulnsoshsdk1167n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshelf',
  );
}
